# MySQL Connection Details
database-ip: 127.0.0.1
database-port: 3306
database-name: Warfare
database-user: user
database-pass: password

# Setting this to false will put the plugin in game server mode
is-lobby: true

# List of lobby servers
lobby-servers:
  - "server"

# GUI menu message for no class slot permission
no-perms-class-slot: "&cNo access"

# The slots and titles for hotbar items
hotbar-items:
  lobby-items:
    shop:
      slot: 3
      title: "&a&lShop"
    class-selector:
      slot: 7
      title: "&b&lSelect Class"
    play:
      slot: 5
      title: "&c&lJoin Game"
  spectator-items:
    teleporter:
      slot: 1
      title: "&a&lTeleporter"
    return-to-lobby:
      slot: 9
      title: "&c&lReturn to Lobby"

# Ultimate Descriptions
description-HEAL:
  - "Heal yourself 3 \u2764"
description-WRATH:
  - "Strike nearby enemies with lightning for 2.5 \u2764"
description-HELLS_SPAWNING:
  - "Spawn a Ghast to assist you in battle"
description-LEAP:
  - "Leap forward & upward"
description-SONIC:
  - "Gain Speed 3 for 5 seconds"
description-WITHERING:
  - "Shoot a wither skull"
description-FLAMING_FEET:
  - "For 5 seconds, you will gain Speed II and"
  - "the blocks below you will be put on fire!"

# Skill Descriptions
description-RESISTANCE:
  - "20% chance to gain Resistance I for 1 second upon being hit"
description-JUGGERNAUT:
  - "Killing an enemy increases your max health by 1 \u2764"
description-CONSUMPTION:
  - "Killing an enemy gives you Regeneration II for 4 seconds"
description-HEAD_START:
  - "Get 10 seconds of Speed II when the game begins"
description-GUARD:
  - "Get Resistance II while in a chest"
description-FLAME:
  - "10% chance for your arrows to be set on fire"

# Health Boost Descriptions
description-HEALTH_BOOST_I:
  - "Gives you an extra heart when you spawn."
description-HEALTH_BOOST_II:
  - "Gives you an extra two hearts when you spawn."
description-HEALTH_BOOST_III:
  - "Gives you an extra three hearts when you spawn."

death-messages:
  melee:
    - "&c%s&7 is victorious over &c%s&7!"
    - "&c%s&7 has overpowered &c%s&7 in combat!"
    - "&c%s&7 evicerated &c%s&7!"
    - "&c%s&7 had fun slicing and dicing &c%s&7!"
    - "&c%s&7 sent &c%s&7 to pay Charon!"
    - "&c%s&7 destroyed &c%s&7!"
    - "&c%s&7 gutted the unfortunate &c%s&7!"
    - "&c%s&7 has sent &c%s&7 to the heavenly realm!"
    - "&c%s&7 showed &c%s&7 the meaning of pain!"
    - "&c%s&7 split &c%s&7 in twain!"
    - "&c%s&7 overcame &c%s&7 in battle!"
    - "&c%s&7 defeated &c%s&7 in mighty struggle!"
    - "&c%s&7 ended all dreams for &c%s&7!"
  bow:
    - "&c%s&7 feathered &c%s&7 with arrows!"
    - "&c%s&7 pierced &c%s&7 using their arrow!"
  diamond_sword:
    - "&c%s&7 sliced through &c%s&7 with a diamond sword!"
    - "&c%s&7 split &c%s&7 in two using a diamond sword!"
  iron_sword:
    - "&c%s&7 slayed &c%s&7 with an iron sword!"
  stone_sword:
    - "&c%s&7 violently bashed the face of &c%s&7 in with a stone sword!"