# MySQL Connection Details
database-ip: 127.0.0.1
database-port: 3306
database-name: Warfare
database-user: user
database-pass: password

# Setting this to false will put the plugin in game server mode
is-lobby: true

# List of lobby servers
lobby-servers:
  - "server"

# GUI menu message for no class slot permission
no-perms-class-slot: "&cNo access"

# The slots and titles for hotbar items
hotbar-items:
  lobby-items:
    shop:
      slot: 3
      title: "&a&lPerk Shop"
    class-selector:
      slot: 7
      title: "&b&lSelect Class"
    play:
      slot: 5
      title: "&6&lJoin Game"
  spectator-items:
    teleporter:
      slot: 1
      title: "&a&lTeleporter"
    return-to-lobby:
      slot: 9
      title: "&c&lReturn to Lobby"

# Ultimate Descriptions
description-HEAL:
  - "Heal yourself 3 \u2764"
description-WRATH:
  - "Strike nearby enemies with lightning for 2.5 \u2764"
description-HELLS_SPAWNING:
  - "Spawn a Ghast to assist you in battle"
description-LEAP:
  - "Leap forward & upward"
description-SONIC:
  - "Gain Speed 3 for 5 seconds"
description-WITHERING:
  - "Shoot a wither skull"
description-FLAMING_FEET:
  - "For 5 seconds, you will gain Speed II and"
  - "the blocks below you will be put on fire!"

# Skill Descriptions
description-RESISTANCE:
  - "20% chance to gain Resistance I for 1 second upon being hit"
description-JUGGERNAUT:
  - "Killing an enemy increases your max health by 1 \u2764"
description-CONSUMPTION:
  - "Killing an enemy gives you Regeneration II for 4 seconds"
description-HEAD_START:
  - "Get 10 seconds of Speed II when the game begins"
description-GUARD:
  - "Get Resistance II while in a chest"
description-FLAME:
  - "10% chance for your arrows to be set on fire"

# Health Boost Descriptions
description-HEALTH_BOOST_I:
  - "Gives you an extra heart when you spawn."
description-HEALTH_BOOST_II:
  - "Gives you an extra two hearts when you spawn."
description-HEALTH_BOOST_III:
  - "Gives you an extra three hearts when you spawn."

death-messages:
  melee:
    - "&6%s&e is victorious over &6%s&e!"
    - "&6%s&e has overpowered &6%s&e in combat!"
    - "&6%s&e evicerated &6%s&e!"
    - "&6%s&e had fun slicing and dicing &6%s&e!"
    - "&6%s&e sent &6%s&e to pay Charon!"
    - "&6%s&e destroyed &6%s&e!"
    - "&6%s&e gutted the unfortunate &6%s&e!"
    - "&6%s&e has sent &6%s&e to the heavenly realm!"
    - "&6%s&e showed &6%s&e the meaning of pain!"
    - "&6%s&e split &6%s&e in twain!"
    - "&6%s&e overcame &6%s&e in battle!"
    - "&6%s&e defeated &6%s&e in mighty struggle!"
    - "&6%s&e ended all dreams for &6%s&e!"
  bow:
    - "&6%s&e feathered &6%s&e with arrows!"
    - "&6%s&e pierced &6%s&e using their arrow!"
  diamond_sword:
    - "&6%s&e sliced through &6%s&e with a diamond sword!"
    - "&6%s&e split &6%s&e in two using a diamond sword!"
  iron_sword:
    - "&6%s&e slayed &6%s&e with an iron sword!"
  stone_sword:
    - "&6%s&e violently bashed the face of &6%s&e in with a stone sword!"