name: Warfare
main: com.andrewyunt.warfare.Warfare
version: 1.0
depend: [Framework]
commands:
  warfare:
    description: The management command for Warfare.
  party:
    description: The command for parties.
  lobby:
    aliases: ['hub']
    description: Return to the lobby server.
  bloodtoggle:
    description: Toggle blood particles on or off.
  setspawn:
    description: Set the spawn location of a lobby with the yaw and pitch.
  coins:
    aliases: ['balance','bal','money']
    description: Check a player's coin balance.
  stats:
    description: View a player's statistics.