name: Warfare
main: com.andrewyunt.warfare.Warfare
version: 1.0
depend: [Framework]
commands:
  warfare:
    description: The management command for Warfare.
  party:
    description: The command for parties.
  lobby:
    aliases: ['hub']
    description: Go to the lobby
  bloodtoggle:
    description: Toggle blood particles on or off.